# format: title and string
#    TITLE_		for different usage
#    string		detail information for every TITLE.
####TITLE_LMKD_SKIP_PROCESS_LIST
##For some benchmark
com.futuremark.dmandroid.application:workload
com.antutu.ABenchMark
com.antutu.ABenchMark.lite
com.antutu.ABenchMark:push
com.antutu.benchmark.full
com.motorola.launcher3
com.antutu.benchmark.full.lite
com.antutu.benchmark.full.lite:unity
com.primatelabs.geekbench5
com.ludashi.benchmark
com.ludashi.benchmark2
com.ludashi.benchmark:pushcore
com.ludashi.benchmark:monitorService
com.ludashi.benchmark:channel
com.antutu.benchmark.full:unity
com.motorola.ccc
com.motorola.ccc.notification
com.motorola.ccc.mainplm
com.motorola.ccc.devicemanagement
com.whatsapp
com.longcheer.SarControl
com.google.android.apps.photos
####TITLE_LMKD_OTHER_CONFIG
